version: "3.9"

services:
  bangla-rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bangla-rag-api
    ports:
      - "10000:10000"
    env_file:
      - .env
    restart: unless-stopped
